package com.triquang.enums;

public enum NotificationType {
    SUSPICIOUS_LOGIN,
    PASSWORD_RESET_REQUESTED,
    BOOKING_CONFIRMED,
    PAYMENT_FAILED,
    BOOKING_REFUNDED,
    TICKET_ISSUED,
    FLIGHT_SCHEDULE_CHANGED,
    AIRLINE_ONBOARDING_DECISION,
    ADMIN_USER_PROVISIONED,
    NOTIFICATION_FAILURE_ALERT
}
