-- Super admin analytics demo bookings
-- Safe to re-run by booking_reference. The rows are intentionally confirmed
-- across several airlines, routes, and months so dashboard charts are visible.

CREATE TEMP TABLE seed_super_admin_bookings (
    booking_reference varchar(255) PRIMARY KEY,
    user_id bigint NOT NULL,
    airline_id bigint NOT NULL,
    flight_id bigint NOT NULL,
    flight_instance_id bigint NOT NULL,
    fare_id bigint NOT NULL,
    trip_type smallint NOT NULL,
    cabin_class varchar(32) NOT NULL,
    total_amount numeric(19, 2) NOT NULL,
    subtotal_amount numeric(19, 2) NOT NULL,
    discount_amount numeric(19, 2) NOT NULL,
    promo_code varchar(32),
    booking_date timestamp NOT NULL,
    contact_email varchar(255) NOT NULL,
    contact_phone varchar(64) NOT NULL
);

INSERT INTO seed_super_admin_bookings VALUES
    ('FHSA-DEMO-001', current_setting('flighthub_seed.customer_minhanh', true)::bigint, current_setting('flighthub_seed.airline_vn', true)::bigint, current_setting('flighthub_seed.flight_vn210', true)::bigint, split_part(current_setting('flighthub_seed.flight_instances_vn210', true), ',', 1)::bigint, current_setting('flighthub_seed.fare_vn210_lite', true)::bigint, 0, 'ECONOMY', 48.00, 48.00, 0.00, NULL, NOW() - INTERVAL '5 days', 'minhanh.nguyen@example.com', '+84920000001'),
    ('FHSA-DEMO-002', current_setting('flighthub_seed.customer_quocbao', true)::bigint, current_setting('flighthub_seed.airline_vn', true)::bigint, current_setting('flighthub_seed.flight_vn210', true)::bigint, split_part(current_setting('flighthub_seed.flight_instances_vn210', true), ',', 2)::bigint, current_setting('flighthub_seed.fare_vn210_flex', true)::bigint, 0, 'ECONOMY', 68.00, 68.00, 0.00, NULL, NOW() - INTERVAL '12 days', 'quocbao.tran@example.com', '+84920000002'),
    ('FHSA-DEMO-003', current_setting('flighthub_seed.customer_hoangphuc', true)::bigint, current_setting('flighthub_seed.airline_vn', true)::bigint, current_setting('flighthub_seed.flight_vn211', true)::bigint, split_part(current_setting('flighthub_seed.flight_instances_vn211', true), ',', 1)::bigint, current_setting('flighthub_seed.fare_vn211_standard', true)::bigint, 0, 'ECONOMY', 60.00, 60.00, 0.00, NULL, NOW() - INTERVAL '18 days', 'hoangphuc.le@example.com', '+84920000003'),
    ('FHSA-DEMO-004', current_setting('flighthub_seed.customer_giahan', true)::bigint, current_setting('flighthub_seed.airline_vn', true)::bigint, current_setting('flighthub_seed.flight_vn218', true)::bigint, split_part(current_setting('flighthub_seed.flight_instances_vn218', true), ',', 1)::bigint, current_setting('flighthub_seed.fare_vn218_saver', true)::bigint, 0, 'ECONOMY', 54.00, 54.00, 0.00, NULL, NOW() - INTERVAL '1 month 3 days', 'giahan.pham@example.com', '+84920000004'),
    ('FHSA-DEMO-005', current_setting('flighthub_seed.customer_thanhdat', true)::bigint, current_setting('flighthub_seed.airline_vj', true)::bigint, current_setting('flighthub_seed.flight_vj122', true)::bigint, split_part(current_setting('flighthub_seed.flight_instances_vj122', true), ',', 1)::bigint, current_setting('flighthub_seed.fare_vj122_saver', true)::bigint, 0, 'ECONOMY', 36.40, 36.40, 0.00, NULL, NOW() - INTERVAL '3 days', 'thanhdat.vo@example.com', '+84920000005'),
    ('FHSA-DEMO-006', current_setting('flighthub_seed.customer_ngoclinh', true)::bigint, current_setting('flighthub_seed.airline_vj', true)::bigint, current_setting('flighthub_seed.flight_vj122', true)::bigint, split_part(current_setting('flighthub_seed.flight_instances_vj122', true), ',', 2)::bigint, current_setting('flighthub_seed.fare_vj122_skyboss', true)::bigint, 0, 'PREMIUM_ECONOMY', 96.40, 96.40, 0.00, NULL, NOW() - INTERVAL '9 days', 'ngoclinh.dang@example.com', '+84920000006'),
    ('FHSA-DEMO-007', current_setting('flighthub_seed.customer_tuankiet', true)::bigint, current_setting('flighthub_seed.airline_vj', true)::bigint, current_setting('flighthub_seed.flight_vj123', true)::bigint, split_part(current_setting('flighthub_seed.flight_instances_vj123', true), ',', 1)::bigint, current_setting('flighthub_seed.fare_vj123_plus', true)::bigint, 0, 'ECONOMY', 38.80, 38.80, 0.00, NULL, NOW() - INTERVAL '1 month 10 days', 'tuankiet.bui@example.com', '+84920000007'),
    ('FHSA-DEMO-008', current_setting('flighthub_seed.customer_phuongthao', true)::bigint, current_setting('flighthub_seed.airline_vj', true)::bigint, current_setting('flighthub_seed.flight_vj803', true)::bigint, split_part(current_setting('flighthub_seed.flight_instances_vj803', true), ',', 1)::bigint, current_setting('flighthub_seed.fare_vj803_asia', true)::bigint, 0, 'ECONOMY', 66.80, 66.80, 0.00, NULL, NOW() - INTERVAL '2 months 4 days', 'phuongthao.do@example.com', '+84920000008'),
    ('FHSA-DEMO-009', current_setting('flighthub_seed.customer_duchuy', true)::bigint, current_setting('flighthub_seed.airline_ak', true)::bigint, current_setting('flighthub_seed.flight_ak520', true)::bigint, split_part(current_setting('flighthub_seed.flight_instances_ak520', true), ',', 1)::bigint, current_setting('flighthub_seed.fare_ak520_low', true)::bigint, 0, 'ECONOMY', 58.00, 58.00, 0.00, NULL, NOW() - INTERVAL '7 days', 'duchuy.hoang@example.com', '+84920000009'),
    ('FHSA-DEMO-010', current_setting('flighthub_seed.customer_khanhvy', true)::bigint, current_setting('flighthub_seed.airline_ak', true)::bigint, current_setting('flighthub_seed.flight_ak521', true)::bigint, split_part(current_setting('flighthub_seed.flight_instances_ak521', true), ',', 1)::bigint, current_setting('flighthub_seed.fare_ak521_low', true)::bigint, 0, 'ECONOMY', 58.00, 58.00, 0.00, NULL, NOW() - INTERVAL '1 month 2 days', 'khanhvy.mai@example.com', '+84920000010'),
    ('FHSA-DEMO-011', current_setting('flighthub_seed.customer_giabao', true)::bigint, current_setting('flighthub_seed.airline_ak', true)::bigint, current_setting('flighthub_seed.flight_ak520', true)::bigint, split_part(current_setting('flighthub_seed.flight_instances_ak520', true), ',', 2)::bigint, current_setting('flighthub_seed.fare_ak520_low', true)::bigint, 1, 'ECONOMY', 116.00, 116.00, 0.00, NULL, NOW() - INTERVAL '2 months 15 days', 'giabao.nguyen@example.com', '+84920000011'),
    ('FHSA-DEMO-012', current_setting('flighthub_seed.customer_minhthu', true)::bigint, current_setting('flighthub_seed.airline_sq', true)::bigint, current_setting('flighthub_seed.flight_sq185', true)::bigint, split_part(current_setting('flighthub_seed.flight_instances_sq185', true), ',', 1)::bigint, current_setting('flighthub_seed.fare_sq185_value', true)::bigint, 0, 'ECONOMY', 136.00, 136.00, 0.00, NULL, NOW() - INTERVAL '4 days', 'minhthu.tran@example.com', '+84920000012'),
    ('FHSA-DEMO-013', current_setting('flighthub_seed.customer_baochau', true)::bigint, current_setting('flighthub_seed.airline_sq', true)::bigint, current_setting('flighthub_seed.flight_sq185', true)::bigint, split_part(current_setting('flighthub_seed.flight_instances_sq185', true), ',', 2)::bigint, current_setting('flighthub_seed.fare_sq185_business', true)::bigint, 0, 'BUSINESS', 428.00, 428.00, 0.00, NULL, NOW() - INTERVAL '23 days', 'baochau.le@example.com', '+84920000013'),
    ('FHSA-DEMO-014', current_setting('flighthub_seed.customer_anhtuan', true)::bigint, current_setting('flighthub_seed.airline_sq', true)::bigint, current_setting('flighthub_seed.flight_sq186', true)::bigint, split_part(current_setting('flighthub_seed.flight_instances_sq186', true), ',', 1)::bigint, current_setting('flighthub_seed.fare_sq186_value', true)::bigint, 0, 'ECONOMY', 136.00, 136.00, 0.00, NULL, NOW() - INTERVAL '3 months 6 days', 'anhtuan.pham@example.com', '+84920000014'),
    ('FHSA-DEMO-015', current_setting('flighthub_seed.customer_myduyen', true)::bigint, current_setting('flighthub_seed.airline_tg', true)::bigint, current_setting('flighthub_seed.flight_tg551', true)::bigint, split_part(current_setting('flighthub_seed.flight_instances_tg551', true), ',', 1)::bigint, current_setting('flighthub_seed.fare_tg551_classic', true)::bigint, 0, 'ECONOMY', 92.00, 92.00, 0.00, NULL, NOW() - INTERVAL '6 days', 'myduyen.vo@example.com', '+84920000015'),
    ('FHSA-DEMO-016', current_setting('flighthub_seed.customer_minhanh', true)::bigint, current_setting('flighthub_seed.airline_tg', true)::bigint, current_setting('flighthub_seed.flight_tg550', true)::bigint, split_part(current_setting('flighthub_seed.flight_instances_tg550', true), ',', 1)::bigint, current_setting('flighthub_seed.fare_tg550_classic', true)::bigint, 0, 'ECONOMY', 92.00, 92.00, 0.00, NULL, NOW() - INTERVAL '2 months 21 days', 'minhanh.nguyen@example.com', '+84920000001'),
    ('FHSA-DEMO-017', current_setting('flighthub_seed.customer_quocbao', true)::bigint, current_setting('flighthub_seed.airline_cx', true)::bigint, current_setting('flighthub_seed.flight_cx764', true)::bigint, split_part(current_setting('flighthub_seed.flight_instances_cx764', true), ',', 1)::bigint, current_setting('flighthub_seed.fare_cx764_essential', true)::bigint, 0, 'ECONOMY', 162.00, 162.00, 0.00, NULL, NOW() - INTERVAL '11 days', 'quocbao.tran@example.com', '+84920000002'),
    ('FHSA-DEMO-018', current_setting('flighthub_seed.customer_hoangphuc', true)::bigint, current_setting('flighthub_seed.airline_cx', true)::bigint, current_setting('flighthub_seed.flight_cx765', true)::bigint, split_part(current_setting('flighthub_seed.flight_instances_cx765', true), ',', 1)::bigint, current_setting('flighthub_seed.fare_cx765_essential', true)::bigint, 0, 'ECONOMY', 162.00, 162.00, 0.00, NULL, NOW() - INTERVAL '4 months 2 days', 'hoangphuc.le@example.com', '+84920000003'),
    ('FHSA-DEMO-019', current_setting('flighthub_seed.customer_giahan', true)::bigint, current_setting('flighthub_seed.airline_vn', true)::bigint, current_setting('flighthub_seed.flight_vn136', true)::bigint, split_part(current_setting('flighthub_seed.flight_instances_vn136', true), ',', 1)::bigint, current_setting('flighthub_seed.fare_vn136_basic', true)::bigint, 0, 'ECONOMY', 43.00, 43.00, 0.00, NULL, NOW() - INTERVAL '2 months 8 days', 'giahan.pham@example.com', '+84920000004'),
    ('FHSA-DEMO-020', current_setting('flighthub_seed.customer_thanhdat', true)::bigint, current_setting('flighthub_seed.airline_vn', true)::bigint, current_setting('flighthub_seed.flight_vn135', true)::bigint, split_part(current_setting('flighthub_seed.flight_instances_vn135', true), ',', 1)::bigint, current_setting('flighthub_seed.fare_vn135_basic', true)::bigint, 0, 'ECONOMY', 43.00, 43.00, 0.00, NULL, NOW() - INTERVAL '3 months 12 days', 'thanhdat.vo@example.com', '+84920000005'),
    ('FHSA-DEMO-021', current_setting('flighthub_seed.customer_ngoclinh', true)::bigint, current_setting('flighthub_seed.airline_vj', true)::bigint, current_setting('flighthub_seed.flight_vj804', true)::bigint, split_part(current_setting('flighthub_seed.flight_instances_vj804', true), ',', 1)::bigint, current_setting('flighthub_seed.fare_vj804_asia', true)::bigint, 0, 'ECONOMY', 66.80, 66.80, 0.00, NULL, NOW() - INTERVAL '4 months 18 days', 'ngoclinh.dang@example.com', '+84920000006'),
    ('FHSA-DEMO-022', current_setting('flighthub_seed.customer_tuankiet', true)::bigint, current_setting('flighthub_seed.airline_sq', true)::bigint, current_setting('flighthub_seed.flight_sq185', true)::bigint, split_part(current_setting('flighthub_seed.flight_instances_sq185', true), ',', 3)::bigint, current_setting('flighthub_seed.fare_sq185_value', true)::bigint, 1, 'ECONOMY', 272.00, 272.00, 0.00, NULL, NOW() - INTERVAL '5 months 5 days', 'tuankiet.bui@example.com', '+84920000007'),
    ('FHSA-DEMO-023', current_setting('flighthub_seed.customer_phuongthao', true)::bigint, current_setting('flighthub_seed.airline_vn', true)::bigint, current_setting('flighthub_seed.flight_vn210', true)::bigint, split_part(current_setting('flighthub_seed.flight_instances_vn210', true), ',', 3)::bigint, current_setting('flighthub_seed.fare_vn210_business', true)::bigint, 0, 'BUSINESS', 188.00, 188.00, 0.00, NULL, NOW() - INTERVAL '5 months 19 days', 'phuongthao.do@example.com', '+84920000008'),
    ('FHSA-DEMO-024', current_setting('flighthub_seed.customer_duchuy', true)::bigint, current_setting('flighthub_seed.airline_cx', true)::bigint, current_setting('flighthub_seed.flight_cx764', true)::bigint, split_part(current_setting('flighthub_seed.flight_instances_cx764', true), ',', 2)::bigint, current_setting('flighthub_seed.fare_cx764_essential', true)::bigint, 1, 'ECONOMY', 324.00, 324.00, 0.00, NULL, NOW() - INTERVAL '6 months 3 days', 'duchuy.hoang@example.com', '+84920000009'),
    ('FHSA-DEMO-025', current_setting('flighthub_seed.customer_khanhvy', true)::bigint, current_setting('flighthub_seed.airline_ek', true)::bigint, current_setting('flighthub_seed.flight_ek393', true)::bigint, split_part(current_setting('flighthub_seed.flight_instances_ek393', true), ',', 1)::bigint, current_setting('flighthub_seed.fare_ek393_saver', true)::bigint, 0, 'ECONOMY', 540.00, 540.00, 0.00, NULL, NOW() - INTERVAL '8 days', 'khanhvy.mai@example.com', '+84920000010'),
    ('FHSA-DEMO-026', current_setting('flighthub_seed.customer_giabao', true)::bigint, current_setting('flighthub_seed.airline_ek', true)::bigint, current_setting('flighthub_seed.flight_ek392', true)::bigint, split_part(current_setting('flighthub_seed.flight_instances_ek392', true), ',', 1)::bigint, current_setting('flighthub_seed.fare_ek392_saver', true)::bigint, 0, 'ECONOMY', 540.00, 540.00, 0.00, NULL, NOW() - INTERVAL '1 month 20 days', 'giabao.nguyen@example.com', '+84920000011'),
    ('FHSA-DEMO-027', current_setting('flighthub_seed.customer_minhthu', true)::bigint, current_setting('flighthub_seed.airline_ek', true)::bigint, current_setting('flighthub_seed.flight_ek393', true)::bigint, split_part(current_setting('flighthub_seed.flight_instances_ek393', true), ',', 2)::bigint, current_setting('flighthub_seed.fare_ek393_saver', true)::bigint, 1, 'ECONOMY', 1080.00, 1080.00, 0.00, NULL, NOW() - INTERVAL '3 months 9 days', 'minhthu.tran@example.com', '+84920000012'),
    ('FHSA-DEMO-028', current_setting('flighthub_seed.customer_baochau', true)::bigint, current_setting('flighthub_seed.airline_qr', true)::bigint, current_setting('flighthub_seed.flight_qr971', true)::bigint, split_part(current_setting('flighthub_seed.flight_instances_qr971', true), ',', 1)::bigint, current_setting('flighthub_seed.fare_qr971_classic', true)::bigint, 0, 'ECONOMY', 520.00, 520.00, 0.00, NULL, NOW() - INTERVAL '10 days', 'baochau.le@example.com', '+84920000013'),
    ('FHSA-DEMO-029', current_setting('flighthub_seed.customer_anhtuan', true)::bigint, current_setting('flighthub_seed.airline_qr', true)::bigint, current_setting('flighthub_seed.flight_qr970', true)::bigint, split_part(current_setting('flighthub_seed.flight_instances_qr970', true), ',', 1)::bigint, current_setting('flighthub_seed.fare_qr970_classic', true)::bigint, 0, 'ECONOMY', 520.00, 520.00, 0.00, NULL, NOW() - INTERVAL '2 months 2 days', 'anhtuan.pham@example.com', '+84920000014'),
    ('FHSA-DEMO-030', current_setting('flighthub_seed.customer_myduyen', true)::bigint, current_setting('flighthub_seed.airline_qr', true)::bigint, current_setting('flighthub_seed.flight_qr971', true)::bigint, split_part(current_setting('flighthub_seed.flight_instances_qr971', true), ',', 2)::bigint, current_setting('flighthub_seed.fare_qr971_classic', true)::bigint, 1, 'ECONOMY', 1040.00, 1040.00, 0.00, NULL, NOW() - INTERVAL '4 months 11 days', 'myduyen.vo@example.com', '+84920000015'),
    ('FHSA-DEMO-031', current_setting('flighthub_seed.customer_minhanh', true)::bigint, current_setting('flighthub_seed.airline_jl', true)::bigint, current_setting('flighthub_seed.flight_jl752', true)::bigint, split_part(current_setting('flighthub_seed.flight_instances_jl752', true), ',', 1)::bigint, current_setting('flighthub_seed.fare_jl752_standard', true)::bigint, 0, 'ECONOMY', 588.00, 588.00, 0.00, NULL, NOW() - INTERVAL '15 days', 'minhanh.nguyen@example.com', '+84920000001'),
    ('FHSA-DEMO-032', current_setting('flighthub_seed.customer_quocbao', true)::bigint, current_setting('flighthub_seed.airline_jl', true)::bigint, current_setting('flighthub_seed.flight_jl751', true)::bigint, split_part(current_setting('flighthub_seed.flight_instances_jl751', true), ',', 1)::bigint, current_setting('flighthub_seed.fare_jl751_standard', true)::bigint, 0, 'ECONOMY', 588.00, 588.00, 0.00, NULL, NOW() - INTERVAL '2 months 14 days', 'quocbao.tran@example.com', '+84920000002'),
    ('FHSA-DEMO-033', current_setting('flighthub_seed.customer_hoangphuc', true)::bigint, current_setting('flighthub_seed.airline_jl', true)::bigint, current_setting('flighthub_seed.flight_jl753', true)::bigint, split_part(current_setting('flighthub_seed.flight_instances_jl753', true), ',', 1)::bigint, current_setting('flighthub_seed.fare_jl753_standard', true)::bigint, 0, 'ECONOMY', 604.00, 604.00, 0.00, NULL, NOW() - INTERVAL '5 months 1 day', 'hoangphuc.le@example.com', '+84920000003');

INSERT INTO bookings (
    booking_reference,
    user_id,
    airline_id,
    flight_id,
    flight_instance_id,
    fare_id,
    trip_type,
    cabin_class,
    flexible_ticket,
    ticket_time_limit,
    status,
    booking_date,
    last_modified,
    ticket_issued,
    total_amount,
    subtotal_amount,
    discount_amount,
    promo_code,
    currency,
    email,
    phone
)
SELECT
    booking_reference,
    user_id,
    airline_id,
    flight_id,
    flight_instance_id,
    fare_id,
    trip_type,
    cabin_class,
    false,
    booking_date + INTERVAL '24 hours',
    'CONFIRMED',
    booking_date,
    booking_date + INTERVAL '15 minutes',
    true,
    total_amount,
    subtotal_amount,
    discount_amount,
    promo_code,
    'USD',
    contact_email,
    contact_phone
FROM seed_super_admin_bookings
ON CONFLICT (booking_reference) DO UPDATE
SET
    user_id = EXCLUDED.user_id,
    airline_id = EXCLUDED.airline_id,
    flight_id = EXCLUDED.flight_id,
    flight_instance_id = EXCLUDED.flight_instance_id,
    fare_id = EXCLUDED.fare_id,
    trip_type = EXCLUDED.trip_type,
    cabin_class = EXCLUDED.cabin_class,
    status = EXCLUDED.status,
    booking_date = EXCLUDED.booking_date,
    last_modified = EXCLUDED.last_modified,
    ticket_issued = EXCLUDED.ticket_issued,
    total_amount = EXCLUDED.total_amount,
    subtotal_amount = EXCLUDED.subtotal_amount,
    discount_amount = EXCLUDED.discount_amount,
    promo_code = EXCLUDED.promo_code,
    currency = EXCLUDED.currency,
    email = EXCLUDED.email,
    phone = EXCLUDED.phone;
