spring:
  application:
    name: seat-service

  config:
    import: optional:configserver:http://localhost:8888

  cloud:
    config:
      fail-fast: true

    openfeign:
      circuitbreaker:
        enabled: true
        group:
          enabled: true

# =========================
# RESILIENCE4J
# =========================
resilience4j:
  circuitbreaker:
    configs:
      default:
        sliding-window-type: COUNT_BASED
        sliding-window-size: 20
        minimum-number-of-calls: 10
        failure-rate-threshold: 50
        slow-call-rate-threshold: 80
        slow-call-duration-threshold: 3000ms
        wait-duration-in-open-state: 30s
        permitted-number-of-calls-in-half-open-state: 5
        automatic-transition-from-open-to-half-open-enabled: true
        register-health-indicator: true
        record-exceptions:
          - java.io.IOException
          - java.util.concurrent.TimeoutException
          - feign.FeignException

    instances:
      AirlineClient:
        base-config: default
        failure-rate-threshold: 60
        wait-duration-in-open-state: 20s

# =========================
# EUREKA
# =========================
eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}

  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/

# =========================
# MANAGEMENT
# =========================
management:
  endpoints:
    web:
      exposure:
        include: health, info

# =========================
# INFO
# =========================
info:
  app:
    name: ${spring.application.name}
    description: Seat management service
    version: 1.0.0