# =============================================================================
# USER SERVICE — Local Configuration
# =============================================================================

eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    register-with-eureka: true
    fetch-registry: true

spring:
  application:
    name: user-service

  profiles:
    active: dev

  config:
    import: optional:configserver:http://localhost:8888

  # ================= KAFKA (PRODUCER) =================
  kafka:
    bootstrap-servers: localhost:9092

    producer:
      acks: all
      retries: 3

      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

      properties:
        spring.json.add.type.headers: true   
        delivery.timeout.ms: 120000
        request.timeout.ms: 30000
        linger.ms: 5
        batch.size: 16384

# ================= TOPIC CONFIG =================
kafka:
  topics:
    suspicious-login: security.suspicious-login

# ================= CUSTOM APP CONFIG =================
app:
  admin:
    password: ${ADMIN_PASSWORD:Admin@123}

# ================= ACTUATOR =================
info:
  app:
    name: ${spring.application.name}
    description: Manages user accounts, profiles, and authentication
    version: 1.0.0
    environment: development

management:
  endpoints:
    web:
      exposure:
        include: health, info
  endpoint:
    health:
      show-details: always
    info:
      enabled: true
  info:
    env:
      enabled: true
    java:
      enabled: true
    os:
      enabled: true