server:
  port: 8089

spring:
  application:
    name: payment-service

  datasource:
    url: jdbc:postgresql://ep-silent-darkness-aoh21u1p-pooler.c-2.ap-southeast-1.aws.neon.tech:5432/flight_hub_payment?sslmode=require
    username: neondb_owner
    password: npg_FDqZpbe3Oml7
    driver-class-name: org.postgresql.Driver

    hikari:
      maximum-pool-size: 3
      minimum-idle: 1
      connection-timeout: 30000

    # LOCAL DB (optional)
    # url: jdbc:postgresql://localhost:5432/flight_hub_booking
    # username: postgres
    # password: 12345678

  jpa:
    hibernate:
      ddl-auto: update   # create / create-drop / validate / update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

  sql:
    init:
      mode: always

payment:
  stripe:
    secret-key: YOU_STRIPE_SECRET_KEY

  paypal:
    client-id: YOU_PAYPAL_CLIENT_ID
    client-secret: YOU_PAYPAL_CLIENT_SECRET
    base-url: https://api-m.sandbox.paypal.com

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE