apiVersion: 1

datasources:
  - name: Prometheus
    uid: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: true

  - name: Loki
    uid: Loki
    type: loki
    access: proxy
    url: http://loki:3100
    editable: true

  - name: Elasticsearch
    uid: Elasticsearch
    type: elasticsearch
    access: proxy
    url: http://elasticsearch:9200
    database: '[flighthub-logs-]YYYY.MM.DD'
    jsonData:
      interval: Daily
      timeField: '@timestamp'
      logMessageField: message
      logLevelField: level
    editable: true
